---
kind: pipeline
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add --no-cache --no-progress make
      - make build
    when:
      event:
        - push
      branch:
        - master

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    depends_on:
      - build
    settings:
      add_modules:
        - "@google/semantic-release-replace-plugin"
      mode: release
      update_readme_toc: true
      git_method: gh
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      update_docker_readme: true
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      docker_repo: cenk1cenk2/do-dyndns
    when:
      event:
        - push
      branch:
        - master

  - name: publish-amd64
    image: plugins/docker
    settings:
      repo: cenk1cenk2/do-dyndns
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BINARY_NAME=linux-x64
      auto_tag: true
    depends_on:
      - semantic-release
    when:
      event:
        - push
      branch:
        - master

  - name: publish-arm
    image: plugins/docker
    settings:
      repo: cenk1cenk2/do-dyndns
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BINARY_NAME=linux-arm
      auto_tag: true
      auto_tag_suffix: linux-arm
    depends_on:
      - semantic-release
    when:
      event:
        - push
      branch:
        - master

  - name: publish-arm64
    image: plugins/docker
    settings:
      repo: cenk1cenk2/do-dyndns
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BINARY_NAME=linux-arm64
      auto_tag: true
      auto_tag_suffix: arm64
    depends_on:
      - semantic-release
    when:
      event:
        - push
      branch:
        - master

---
kind: pipeline
type: docker
name: manifest

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    auto_tag: true
    ignore_missing: true
    spec: .manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
    - push
  branch:
    - master

depends_on:
- publish-arm
- publish-arm64