---
kind: pipeline
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add --no-cache --no-progress make
      - make build
    when:
      event:
        - push
      branch:
        - master

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    depends_on:
      - build
    settings:
      add_modules:
        - '@google/semantic-release-replace-plugin'
      mode: release
      update_readme_toc: true
      git_method: gh
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      update_docker_readme: true
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      docker_repo: cenk1cenk2/do-dyndns
    when:
      event:
        - push
      branch:
        - master

  - name: docker-build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker version
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker buildx  - apk add curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - docker info
      - docker info create --use --name builder
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t cenk1cenk2/do-dyndns:latest --push .
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      BUILDX_VERSION: 0.5.1
    depends_on:
      - semantic-release
    when:
      event:
        - push
      branch:
        - master

services:
  - name: docker
    image: docker:dind
    command: --experimental
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

    # - name: publish-arm
    #   image: plugins/docker
    #   settings:
    #     repo: cenk1cenk2/do-dyndns
    #     username:
    #       from_secret: docker_username
    #     password:
    #       from_secret: docker_password
    #     build_args:
    #       - IMAGE_NAME=arm32v7/alpine
    #       - BINARY_NAME=linux-arm
    #     tags:
    #       - arm
    #   depends_on:
    #     - semantic-release
    #   when:
    #     event:
    #       - push
    #     branch:
    #       - master
    #
    # - name: publish-arm64
    #   image: plugins/docker
    #   settings:
    #     repo: cenk1cenk2/do-dyndns
    #     username:
    #       from_secret: docker_username
    #     password:
    #       from_secret: docker_password
    #     build_args:
    #       - IMAGE_NAME=arm64v8/alpine
    #       - BINARY_NAME=linux-arm64
    #     tags:
    #       - arm64
    #   depends_on:
    #     - semantic-release
    #   when:
    #     event:
    #       - push
    #     branch:
    #       - master
    #
    # - name: manifest-arm
    #   image: plugins/manifest
    #   settings:
    #     username:
    #       from_secret: docker_username
    #     password:
    #       from_secret: docker_password
    #     target: cenk1cenk2/do-dyndns:arm
    #     template: cenk1cenk2/do-dyndns:ARCH
    #     platforms:
    #       - linux/arm
    #     ignore_missing: true
    #   depends_on:
    #     - publish-arm
    #
    # - name: manifest-arm64
    #   image: plugins/manifest
    #   settings:
    #     username:
    #       from_secret: docker_username
    #     password:
    #       from_secret: docker_password
    #     target: cenk1cenk2/do-dyndns:arm64
    #     template: cenk1cenk2/do-dyndns:ARCH
    #     platforms:
    #       - linux/arm64
    #     ignore_missing: true
    #   depends_on:
    #     - publish-arm64
