---
kind: pipeline
trigger:
  event:
    - push
    - tag
  branch:
    - master

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add --no-cache --no-progress make
      - make build

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      add_modules:
        - "@google/semantic-release-replace-plugin"
      mode: release
      update_readme_toc: true
      git_method: gh
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      update_docker_readme: true
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      docker_repo: cenk1cenk2/do-dyndns
    when:
      event:
        - push
      branch:
        - master

  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/do-dyndns
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
      branch:
        - master
