stages:
  - install
  - publish
  - build
  - docker
  - post

variables:
  DOCKERFILE_CONTEXT: .
  DOCKER_IMAGE_NAME: cenk1cenk2/do-dyndns
  DOCKER_USE_BUILDX: "true"
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  TAGS_FILE: ".tags"
  README_DESCRIPTION: |
    Use dynamic DNS through Digital Ocean API for your domains.

include:
  - project: devops/pipes
    file: /templates/go-install.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/go-build.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml
    ref: main

semantic-release:
  artifacts:
    paths:
      - version/v.go
      - .tags

build-docker-image:
  only:
    refs:
      - master
